{{- if and .Values.ssl.enabled (not .Values.ssl.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-ssl" (include "rsky-relay.fullname" .) }}
  namespace: {{ include "rsky-relay.namespace" . | quote }}
  labels:
    {{- include "rsky-relay.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- if .Values.ssl.cert }}
  tls.crt: {{ .Values.ssl.cert | b64enc }}
  {{- else }}
  tls.crt: ""
  {{- end }}
  {{- if .Values.ssl.key }}
  tls.key: {{ .Values.ssl.key | b64enc }}
  {{- else }}
  tls.key: ""
  {{- end }}
{{- end }}